version: '3.3'
services:
        web:
                build:
                        context: ./php
                        dockerfile: Dockerfile
                container_name: php73
                depends_on:
                        - db
                volumes:
                        - ./php:/var/www/html/
                ports:
                        - 80:80
        db:
                container_name: newmysqldb5
                image: mysqldb
                restart: always
                command: --default_authentication_plugin=mysql_native_password
                environment:
                        MYSQL_ROOT_PASSWORD: 12345
                        MYSQL_USER:  root
                        MYSQL_PASSWORD: 12345
                        #MYSQL_DATABASE: team_record
                ports:
                        - 6033:3306

